### ISSUE TITLE
Implement ```annualized return```, ```alpha``` data columns for various investment periods after 8-K release

### ISSUE THREAD

**Issue by kamilkrukowski** [kamilkrukowski/sec-sentiment-pred#15]
We want the moving average columns from [14](https://github.com/kamilkrukowski/sec-sentiment-pred/issues/14) to be expanded upon. Specifically, we want to 

1. Annualize the return over the investment period (7, 30, 90) day comparing purchase the day after with sale at the 7,30,90 day marks. This should be a new data column. It would be nice if it was included in the ```generate_labels.py``` script.

2. Get reference annualized returns for the S&P 500 over the same time period. Realistically, this should be a function with some documentation string that is easily importable by other scripts.

3. Calculate ```Alpha``` of investment over period. This is a relative advantage in annualized return with respect to the S&P500 returns. This can be a new data column, and it would be nice if it was included in ```generate_labels.py```. Ideally, the function should be documented and easily importable by other scripts. We want this function to ultimately report model performance dynamically downstream when called by model-builders.

**Comment by yyitingli** [comment]
download [CPI Data](https://tufts.box.com/s/565js9mmll075a0uzylj83ljgm5gb7m1).
