### ISSUE TITLE
stock-prediction branch does not annualize the output

### ISSUE THREAD

**Issue by kamilkrukowski** [kamilkrukowski/sec-sentiment-pred#3]
```stock-prediction-branch``` get annual return function currently returns a multiplier of value over the elapsed time period. It should be standardized to annualize the return, regardless of time period involved.

**Comment by yyitingli** [comment]
<img width="593" alt="Screen Shot 2023-03-10 at 2 34 02 PM" src="https://user-images.githubusercontent.com/66972539/224440795-f8162c12-b993-4f70-b8c6-8dcbd8eed992.png">
should we use this function ? n = number of year

**Comment by kamilkrukowski** [comment]
that would be a correct mathematical interpretation. ```n``` can be a float calculated as a fractional number of years over the elapsed period of days, from the user-provided ```end_date``` and ```start_date```
