### ISSUE TITLE
stock-prediction branch contains unstable data file

### ISSUE THREAD

**Issue by kamilkrukowski** [kamilkrukowski/sec-sentiment-pred#4]
```TIKR_Data.pkl``` is a data file. Github does not offer to store data files. In fact, this files happens to take up 95% of the memory GitHub allows for file upload. This means that a new ```TIKR_Data.pkl``` associated with a few more companies is too big to upload to GitHub, and the current one is always downloaded by everyone due to history tracking.

1. We should figure out a data sharing method if we want to exchange this file.

2. This file should be deleted from history.

**Comment by yyitingli** [comment]
-TIKR_Data.pkl is uploaded to google drive.
-It is removed from the branch.

**Comment by kamilkrukowski** [comment]
@yyitingli This needs a rebase to fix --> Whenever you git pull you download ALL commits, including the commits that contain this file, even though now future and current commits no longer contain it.

the most notable impact on my end today is whenever I upload a new branch or force push my branch after rebasing it downloads/uploads the history of the 45MB file which slows it down a lot.

**Comment by kamilkrukowski** [comment]
```TIKR_Data.pkl``` is still publicly viewable in our git history and downloaded if we pull this branch.

**Comment by yyitingli** [comment]
I just rebase
