### ISSUE TITLE
stock-prediction branch nomenclature, remove todos

### ISSUE THREAD

**Issue by kamilkrukowski** [kamilkrukowski/sec-sentiment-pred#6]
Can we standardize some of the names in the ```portfolio_eval.py``` stock simulator class?

From my understanding, active balance is not a GAAP term, nor do we have an explicit definition. However, my understanding is that we are using it in the same exact manner as (Net Worth, Total Assets) which are GAAP terms that are commonly known.

If we could remove the commented out code, unused imports, and #TODOS that would be great.

**Comment by yyitingli** [comment]
change active_balance to get_net_worth

**Comment by kamilkrukowski** [comment]
Seems ready for a pull request, other issues are feature requests.

**Comment by kamilkrukowski** [comment]
Seems done?
