### ISSUE TITLE
```generate_labels.py``` verbose output

### ISSUE THREAD

**Issue by kamilkrukowski** [kamilkrukowski/sec-sentiment-pred#8]
Currently, whenever the label_generation is run for a non-trivial number of inputs, the terminal is flooded by

```[*********************100%***********************]  1 of 1 completed```
occurring hundreds of times. Can this be silenced? Could we get a perfectly normal ```tqdm``` loading bar instead?

------EDIT-----------

It really would help to know whether this function will take 15 seconds or 20 minutes. As the dataset size increases, the range of possible runtimes will only widen.

**Comment by yyitingli** [comment]
this could be silence if you set  yf.download( tikr,  progress= False)

**Comment by kamilkrukowski** [comment]
Does yf.download actually download new data? I thought the code should re-use ```TIKRS_Data.pkl```?

------------EDIT--------------
Yes of course it downloads new data. But why does it run every time I run the script? @kelseyyew I thought it caches and uses ```TIKRS_Data.pkl```?

**Comment by kelseyyew** [comment]
the filename is called 'TIKR_DATA.pickle' but it should download if 'TIKR_DATA.pickle' does not exist. Once it exists, it will download the pickle file instead of redownloading it.

**Comment by kamilkrukowski** [comment]
1. Sorry, what do you mean download the local pickle file?

2. It seems we are at least downloading some ticker called "^GSPC"

<img width="428" alt="Screenshot 2023-03-13 at 1 25 13 PM" src="https://user-images.githubusercontent.com/25352646/224779821-883dea46-e59c-4460-9c67-6f20306385a7.png">

Okay, it turns out that the terminal was reprinting the download message dozens of times due to a bug from ```tqdm``` in the version of yfinance I had installed. I've updated ```tqdm``` and I'm down to 1 download message.

**Comment by kelseyyew** [comment]
^GSPC is the S&P 500. I can make edits so we only need to download that once. 
The pickle file only needs to be created once. This is ALL historical price data for all tikrs. Once that is done, then we can use  the pickle file to get historical data.
